### ISSUE TITLE
Can you share the detail of your device ?

### ISSUE THREAD

**Issue by jacky22043** [PeiqinZhuang/API-Net#2]
What GPU do you use ? and how much memory  this project need ?

**Comment by PeiqinZhuang** [comment]
Hi, you may need 8 1080Ti GPUs when you use ResNet101 as your backbone. I do not remember the exact figure for the memory, but the devices almost run at full capacity.

**Comment by jacky22043** [comment]
Thank for your response. So, Do you mean It need 88GB(8*11GB) memory of GPUs? How long did training take ?

**Comment by PeiqinZhuang** [comment]
Almost. However, you are recommended to reduce the number of samples within the same class if you have fewer GPUs. Please refer to Table 5 in our paper for more details. The training process(CUB_200_2011) typically takes less than 10 hours as far as I remember.

**Comment by jacky22043** [comment]
Okay, thanks for really great work and very quick response.
