### ISSUE TITLE
Could your model for image matching?

### ISSUE THREAD

**Issue by knaffe** [PeiqinZhuang/API-Net#3]
Hello, I have read your paper and your code. Thanks for you great job.
I want to use your model in image matching task. My dream model is:  input is 2 images, and output is their match score, just as your training phase.
I review your code and your paper, and find that: this model is required the one image and output score is <Pooling feat + FC> while testing. 
My question is: If I use an image pair(2 images) to get the final score from your model, would this model work find in the fine-grained dataset? 
Thank you.

**Comment by knaffe** [comment]
By the way, does the last FC of train/test share params? So, if changing the input order, would the model work fine?

**Comment by PeiqinZhuang** [comment]
I think it may work for the situation you described, although I have not tried this before. I recommend you to train your dataset with our method, and then use the backbone to extract features by removing the final fc layer, to check if the quality of features is improved.
