### ISSUE TITLE
How much GPU memory do you need？

### ISSUE THREAD

**Issue by amusingchao** [PeiqinZhuang/API-Net#4]
If you use class size 30.sample images 4. The batch number is 120. It is so big.

**Comment by PeiqinZhuang** [comment]
You are right. On one hand, it is inconvenient to sample a number of samplers when you have a few GPUs. On the other hand, it is essential to adopt this strategy when you want to enrich the sample diversity in one batch.  Alternatively, you can choose to reduce the input resolution or the number of samples within the same class. I think it may alleviate the situation. We have conducted ablation studies on how to select class size & image size in our paper. Please refer to it.
